# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-07 15:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_name', models.CharField(help_text='Expense Name', max_length=255)),
                ('charges', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Installations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Installations Name', max_length=100)),
                ('company', models.CharField(max_length=55)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('expenses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Expenses')),
            ],
        ),
        migrations.CreateModel(
            name='Repairs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repair_name', models.CharField(help_text='Repair Name', max_length=100)),
                ('repair_date', models.DateTimeField()),
                ('company', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('expenses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Expenses')),
            ],
        ),
        migrations.AddField(
            model_name='installations',
            name='repairs',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='projects.Repairs'),
        ),
    ]
