# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-10 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20180610_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='repairs',
            name='cost',
            field=models.CharField(default='none', max_length=55),
        ),
        migrations.AlterField(
            model_name='repairs',
            name='installation_name',
            field=models.CharField(help_text='installation_Name', max_length=100),
        ),
    ]
