# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-12 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20180610_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='expense_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='installations',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='repairs',
            name='installation_name',
            field=models.CharField(max_length=100),
        ),
    ]
