# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-14 18:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20180612_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repairs',
            old_name='installation_name',
            new_name='repair_name',
        ),
    ]
