# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-14 18:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20180614_1804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='installations',
            old_name='name',
            new_name='installation_name',
        ),
    ]
